### ISSUE TITLE
Create a public chat page with Stream

### ISSUE THREAD

**Issue by rishi-raj-jain** [rishi-raj-jain/next.rishi.app#35]
use https://getstream.io/ to create a page where any [guest user](https://getstream.io/chat/docs/react/authless_users/#guest-users) can come and drop a message, it'd be a cool to have!

so this'd involve the following steps as I think in a React component:

- creating a channel with Stream (use a single channel and not re-create it every time for each new user)
- creating a unique user based on their IP / localStorage variable, then allow them to post a message
- render the messages as text in `<ul>`

note: 

- nothing to be done on server-side
- won't be able to assign, feel free to create PRs directly to be reviewed
- only create finished PR or put them in draft state

**Comment by algora-pbc** [comment]
💎 **rishi-raj-jain** is offering a **$35** bounty for this issue
👉 Got a pull request resolving this? Claim the bounty by adding `@algora-pbc /claim #35` in the PR body and joining algora.io

**Comment by mrkirthi-24** [comment]
@rishi-raj-jain what is the deadline?

**Comment by rishi-raj-jain** [comment]
would be great to have it by 18th 3 PM IST

**Comment by rishi-raj-jain** [comment]
@mrkirthi-24 

Did you get a chance at it?

**Comment by mrkirthi-24** [comment]
> Did you get a chance at it?

Yeah going through the docs.

**Comment by rishi-raj-jain** [comment]
@mrkirthi-24 

Any progress?

**Comment by rishi-raj-jain** [comment]
If not, feel free to say so, it's all fine.

**Comment by mrkirthi-24** [comment]
> If not, feel free to say so, it's all fine.

I am actually working in a job. So, once I get time, I will work on it

**Comment by rishi-raj-jain** [comment]
yup totally fine, I wanted to take a look myself so will work on this, thanks!
